### PR TITLE
Aeson-2.0 support

### LINKED ISSUE #9: aeson-2.0 compatibility?
Hi, I noticed `yaml-combinators` doesn't currently build against `aeson-2.0`. Thanks.

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This PR adds support for aeson-2.0 (fixes #9).

I didn't manage to get this fully working - doctests are failing:

```
src/Data/Yaml/Combinators/AesonCompat.hs:14:5: error:
     error: function-like macro 'MIN_VERSION_aeson' is not defined
   |
14 | #if MIN_VERSION_aeson(2,0,0)
   |     ^
#if MIN_VERSION_aeson(2,0,0)
    ^
1 error generated.

src/Data/Yaml/Combinators/AesonCompat.hs:1:1: error:
    `gcc' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | {-# LANGUAGE CPP #-}
  | ^
```

It seems they don't have access to the `MIN_VERSION_<package>` macro that I used to detect the `aeson` version with CPP. I think there are a few options here...

1. Keep digging in to make this work
2. Remove doctest suite
3. Only support aeson > 2.0 moving forward, eliminating all of the CPP.

Let me know what you think! Thanks.

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
@UnkindPartition Any interest in getting this one through?

**Comment by UnkindPartition** [comment]
Hey, sorry, I'm in the army and don't have time for this. I'll make you a maintainer here and on hackage so you can take care of it.

**Comment by mitchellwrosen** [comment]
Ok! Sounds good, thank you

**Comment by mitchellwrosen** [comment]
I had quite a bit of difficulty running the doctests even after removing the aeson CPP, so I went ahead and moved all of the doctests into the tasty test suite. Now they're just comments in the haddocks, but I think that's okay.

**Pull request merged**
